### ISSUE TITLE
Move to libkeepass group

### ISSUE THREAD

**Issue by Evidlo** [libkeepass/pykeepass#100]
How would you feel about moving this repo to the libkeepass group?  It would be nice to have a higher [bus factor](http://wikipedia.org/wiki/Bus_factor) than 1.

**Comment by pschmitt** [comment]
That would not increase the bus factor. @phpwutz is the sole owner of the libkeepass org. 
See https://github.com/libkeepass/libkeepass/pull/18

If that were to change I would not mind migrating.

**Comment by Evidlo** [comment]
I've made you an owner of the libkeepass group.

**Comment by pschmitt** [comment]
Great, I think we can close this then ;)

**Comment by Evidlo** [comment]
@pschmitt I'm going to start merging PR's if you don't mind.

**Comment by Evidlo** [comment]
@pschmitt Any chance I could get added to pypi so I can make a release?

**Comment by Evidlo** [comment]
@pschmitt Bump

**Comment by pschmitt** [comment]
@Evidlo sure thing. What's your nick on pypi?

**Comment by Evidlo** [comment]
Evidlo

**Comment by pschmitt** [comment]
Done.
