### ISSUE TITLE
save() is not thread safe

### ISSUE THREAD

**Issue by loupianche** [libkeepass/pykeepass#101]
If a program save db in a thread while crashing in main thread, the result is an empty DB file.

save() should write to a tmp file and move result to original once done.

**Comment by loupianche** [comment]
Rewritten save() using Gio safe functions.
https://gitlab.gnome.org/gnumdk/passbook/blob/keepass/passbook/keepass_collection.py#L147

Don't know if an equivalent exists in python default lib.

**Comment by Evidlo** [comment]
@loupianche bump

**Comment by KeyWeeUsr** [comment]
I think @loupianche moved to https://gitlab.gnome.org/gnumdk, not sure how to contact him.

**Comment by bellegarde-c** [comment]
Hmm, sorry, it's fixed, you can close.
