### ISSUE TITLE
Feature request: Support field references

### ISSUE THREAD

**Issue by philipsd6** [libkeepass/pykeepass#108]
```python
In [9]: kp.find_entries(title='Test Entry', first=True).password
Out[9]: '{REF:P@I:49EF54B695EB3E4591F3F07D26D4124C}'
```
Ideally, this would automatically dereference that and return the password, or there should be methods to track it down, like maybe:
```python
kp.deref(entry.password)
```
Ultimately, there should also be a method to link one entry's field to another entry's field, perhaps like:
```python
existing_entry = kp.find_entries(title='Production Entry', first=True)
url = 'https://test-site.example.com/?user=%s' % existing_entry.ref('username')
new_entry = kp.add_entry('Testing',
                         title='Test Entry',
                         username=existing_entry.ref('username'),
                         password=existing_entry.ref('password'),
                         url=url)
```

**Comment by philipsd6** [comment]
On a related note, why are the uuids not in the same format as in Keepass2? Trying to do this manually doesn't work:
```python
In [33]: kp.find_entries(uuid='49EF54B695EB3E4591F3F07D26D4124C')
Out[33]: []
```
But this works:
```python
In [34]: kp.find_entries(uuid='Sd9UpoArPkWA4/C/F9QZSw==')
Out[34]: [b'Entry: "Work/Production Entry (testuser)"']
```
How to convert from one uuid format to the other, and why should the end user do that?

**Comment by Evidlo** [comment]
The way you convert is with `base64.b64encode()` and `base64.b64decode()`.  They are base64 encoded because that's how they are stored in XML.

I'll look into converting it automatically in the next few days.

**Comment by Evidlo** [comment]
I don't understand your first post.  Is `{REF:P@I:49EF54B695EB3E4591F3F07D26D4124C}` some string being generated by your password manager? That's definitely not anything on our side.

**Comment by philipsd6** [comment]
@Evidlo That string is standard Keepass2 field reference stuff: https://keepass.info/help/base/fieldrefs.html

In the Windows Keepass2 app, `{REF:P@I:49EF54B695EB3E4591F3F07D26D4124C}` returns the **P**assword from the entry referenced by the given UU**I**D

**Comment by Evidlo** [comment]
Support added by #178
