### ISSUE TITLE
auto type sequence does not check for None

### ISSUE THREAD

**Issue by whwright** [libkeepass/pykeepass#117]
```python
>>> from pykeepass import PyKeePass
>>> kp = PyKeePass('REDACTED', password='REDACTED')
>>> for entry in kp.find_entries(title='something without autotype'):
...     print(entry.autotype_sequence)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/whw/Dev/pykeepass/pykeepass/entry.py", line 180, in autotype_sequence
    return self._element.find('AutoType/DefaultSequence').text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by Evidlo** [comment]
Can be closed

**Comment by firecat53** [comment]
I'm still occasionally seeing this error triggered when [editing autotype entries](https://github.com/firecat53/keepmenu/issues/31) from keepmenu. Seems like it's from databases that are older and don't have the 'DefaultSequence' key in them already.

Workaround is to export database using KeepassXC (or equivalent, I assume) and import to a newly created database.
