### ISSUE TITLE
Protected String fields loose internal whitespace/newline

### ISSUE THREAD

**Issue by ThorbenJ** [libkeepass/pykeepass#129]
Hi,

We have entries with additional string fields that are multi-lined (i.e. contain new lines). We have found that if you mark the string field as memory protected it will loose its white space, when read via pykeepass (but not in keepass2). In particular the multi-line strings will become a single line string. "Unprotected" string fields keep their formatting, via pykeepass.

BR,
Thorben

**Comment by Evidlo** [comment]
I fixed this in the `multiline` branch.  Can you tell me if this works for you?

**Comment by Evidlo** [comment]
@ThorbenJ bump
