### ISSUE TITLE
regression in master: AttributeError: 'PyKeePass' object has no attribute 'kdbx'

### ISSUE THREAD

**Issue by singuliere** [libkeepass/pykeepass#137]
The following

    entries = []
    with PyKeePass(filename, password=password, keyfile=keyfile) as kp:
         entries.extend(kp.entries)
    entries[0].expiry_time

raises an exception as of 193b39177f79d2d616daab5c7da3a3146f725986:

    File "pykeepass/pykeepass/baseelement.py", line 179, in expiry_time
     return self._get_times_property('ExpiryTime')
    File "pykeepass/pykeepass/baseelement.py", line 149, in _get_times_property
      return self._decode_time(prop.text)
    File "pykeepass/pykeepass/baseelement.py", line 123, in _decode_time
      if self._kp.version >= (4, 0):
    File "pykeepass/pykeepass/pykeepass.py", line 83, in version
      self.kdbx.header.value.major_version,

because the kdbx data member is [removed by \_\_exit__](https://github.com/pschmitt/pykeepass/blob/193b39177f79d2d616daab5c7da3a3146f725986/pykeepass/pykeepass.py#L49). This regression was introduced in [the attachment implementation](https://github.com/pschmitt/pykeepass/pull/126) which [keeps a reference to the PyKeePass object](https://github.com/pschmitt/pykeepass/pull/126/files#diff-c95e006146be0e4b924d2ee431dd1b8dR89) and relies on its implementation of the **version** attribute which requires the **kdbx** data member.

**Comment by singuliere** [comment]
@Evidlo here is one use case: https://github.com/pschmitt/vault-keepass-import/blob/master/keepass_import.py#L89 (using libkeepass) which is converted to using pykeepass at https://github.com/singuliere/vault-keepass-import/blob/update/vault_keepass_import/main.py#L35

However, even if there was no known use case it would still be a regression that needs fixing, don't you think?

**Comment by Evidlo** [comment]
> However, even if there was no known use case it would still be a regression that needs fixing, don't you think?

We've always assumed the database will be open while accessing entries/groups, so I think this falls under 'undefined behavior'.  You should convert the entries into primitives while inside the context manager.

**Comment by singuliere** [comment]
Would you be open to the idea of a pull request implementing *copy* method for the entry that would return a copy of the object that does not rely on the underlying database? I could implement such a function in my own code. But it looks like something other people could use and better implemented in pykeepass itself. I may not be the only one stumbling on this unexpected behavior.

**Comment by singuliere** [comment]
> We've always assumed the database will be open while accessing entries/groups...

I see that b88f4dccd4430aa45e928f478d707ed2efd48f80 dated January 8th, 2019, added the **_kp** data member to the Entry class. Could you please explain in what way the Entry instances assumed the database to be open while accessing them prior to this commit? I'm not seeing it but ... I'm not very familiar with the codebase :-)

**Comment by Evidlo** [comment]
To be honest, there's not much point in the context manager anyways because the file descriptor is closed immediately: https://github.com/construct/construct/blob/master/construct/core.py#L320-L325

This raises an important point.  I think the context manager either should be deleted or modified to delete the whole database, not just `kdbx`.

> added the _kp data member to the Entry class
This is because attachment data is stored outside of the entry in KeePass, so `Entry` needs access to the rest of the database.

I think your problem will go away if you use `kp = PykeePass(...)` instead.

**Comment by singuliere** [comment]
> I think your problem will go away if you use kp = PykeePass(...) instead.

That's what I ended up doing, indeed. I suppose an update of the documentation would be good enough to fix this issue.

**Comment by Evidlo** [comment]
Yes, I'll update the documentation and remove the section about the context manager.  I'll also turn __enter__ and __exit__ into no-ops.
