### ISSUE TITLE
No module named kdbx_parsing.kdbx

### ISSUE THREAD

**Issue by Bastilla123** [libkeepass/pykeepass#144]
I write a littel skript:

from pykeepass import PyKeePass

# load database
kp = PyKeePass('neue.kdbx', password='Password1234')

Result:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pykeepass import PyKeePass
  File "/home/sebastian/Downloads/pykeepass-master/pykeepass/pykeepass.py", line 16, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
ImportError: No module named kdbx_parsing.kdbx

i don't understand in pykeepass.py the row:

from pykeepass.kdbx_parsing.kdbx import KDBX

**Comment by jugmac00** [comment]
Hi @Bastilla123 

You are importing erroneously from the module pykeepass instead from the package, see my screenshot.

![screenshot from 2019-03-07 19-50-04](https://user-images.githubusercontent.com/9895620/53981117-3a9b8c00-4112-11e9-8f91-fd54593261a4.png)

**Comment by Bastilla123** [comment]
Thank you very much. I'm beginner in python.

**Comment by Evidlo** [comment]
Can this be closed?

**Comment by Bastilla123** [comment]
Yes. Thanks

Evan Widloski <notifications@github.com> schrieb am Di., 19. März 2019,
04:07:
