### ISSUE TITLE
missing positional argument TypeError when packaging pykeepass

### ISSUE THREAD

**Issue by cap44** [libkeepass/pykeepass#158]
PyKeePass 3.0.3
Python 3.6 
openSUSE 15.1 Leap

Building/packaging pykeepass on openSUSE 15.1 and python 3.6 throws this error:
```
[   61s] Traceback (most recent call last):
[   61s]   File "setup.py", line 24, in <module>
[   61s]     include_package_data=True
[   61s]   File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
[   61s]     return distutils.core.setup(**attrs)
[   61s]   File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
[   61s]     dist.run_commands()
[   61s]   File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
[   61s]     self.run_command(cmd)
[   61s]   File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
[   61s]     cmd_obj.run()
[   61s]   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 228, in run
[   61s]     self.run_tests()
[   61s]   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 250, in run_tests
[   61s]     exit=False,
[   61s]   File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
[   61s]     self.parseArgs(argv)
[   61s]   File "/usr/lib64/python3.6/unittest/main.py", line 118, in parseArgs
[   61s]     self._do_discovery(argv[2:])
[   61s]   File "/usr/lib64/python3.6/unittest/main.py", line 229, in _do_discovery
[   61s]     self.test = loader.discover(self.start, self.pattern, self.top)
[   61s]   File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
[   61s]     tests = list(self._find_tests(start_dir, pattern))
[   61s]   File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
[   61s]     full_path, pattern, namespace)
[   61s]   File "/usr/lib64/python3.6/unittest/loader.py", line 475, in _find_test_path
[   61s]     tests = self.loadTestsFromModule(package, pattern=pattern)
[   61s]   File "/usr/lib/python3.6/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
[   61s]     tests.append(self.loadTestsFromName(submodule))
[   61s]   File "/usr/lib64/python3.6/unittest/loader.py", line 153, in loadTestsFromName
[   61s]     module = __import__(module_name)
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/tests/tests.py", line 8, in <module>
[   61s]     from pykeepass import icons, PyKeePass
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/__init__.py", line 2, in <module>
[   61s]     from .pykeepass import PyKeePass
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/pykeepass.py", line 15, in <module>
[   61s]     from pykeepass.kdbx_parsing.kdbx import KDBX
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
[   61s]     from .kdbx import KDBX
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/kdbx.py", line 2, in <module>
[   61s]     from .kdbx3 import DynamicHeader as DynamicHeader3
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/kdbx3.py", line 10, in <module>
[   61s]     from .common import (
[   61s]   File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/common.py", line 326, in <module>
[   61s]     'chacha20': b'\xd6\x03\x8a+\x8boL\xb5\xa5$3\x9a1\xdb\xb5\x9a'
[   61s] TypeError: __init__() missing 1 required positional argument: 'encoding' 
```

What's throwing this error?

**Comment by Evidlo** [comment]
I have no idea what `init()` function that traceback is referring to.  Does this error still happen when you import `pykeepass.PyKeePass` in the shell?

**Comment by cap44** [comment]
@Evidlo Apologies, I've updated the stack trace in the original post

``

**Comment by Evidlo** [comment]
Does this error happen if you manually import `PyKeePass` or manually run the tests?

I think this error is being raised by [StringEncoded](https://github.com/construct/construct/blob/master/construct/core.py#L1497-L1517), but the traceback isn't providing any info on where this class is called from.

**Comment by cap44** [comment]
@Evidlo Yes, the error is also raised when I run the `python3 setup.py test` command manually.

**Comment by Evidlo** [comment]
And what if you do `from pykeepass import PyKeePass` in the shell?  Can you paste that traceback?

**Comment by cap44** [comment]
Python 3.6.5 stack trace:
`Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykeepass import PyKeePass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/pykeepass.py", line 15, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/kdbx.py", line 2, in <module>
    from .kdbx3 import DynamicHeader as DynamicHeader3
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/kdbx3.py", line 10, in <module>
    from .common import (
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/common.py", line 326, in <module>
    'chacha20': b'\xd6\x03\x8a+\x8boL\xb5\xa5$3\x9a1\xdb\xb5\x9a'
TypeError: __init__() missing 1 required positional argument: 'encoding'`

Python 2.7.14 stack trace:
`Python 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykeepass import PyKeePass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass
  File "pykeepass/pykeepass.py", line 15, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File "pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File "pykeepass/kdbx_parsing/kdbx.py", line 2, in <module>
    from .kdbx3 import DynamicHeader as DynamicHeader3
  File "pykeepass/kdbx_parsing/kdbx3.py", line 10, in <module>
    from .common import (
  File "pykeepass/kdbx_parsing/common.py", line 326, in <module>
    'chacha20': b'\xd6\x03\x8a+\x8boL\xb5\xa5$3\x9a1\xdb\xb5\x9a'
TypeError: __init__() takes at least 4 arguments (3 given)`

'abuild' is the user that performs the automatic build process when the command `osc build` is called

**Comment by cap44** [comment]
This is the python 3 trace:

`Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykeepass import PyKeePass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/pykeepass.py", line 15, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/kdbx.py", line 2, in <module>
    from .kdbx3 import DynamicHeader as DynamicHeader3
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/kdbx3.py", line 10, in <module>
    from .common import (
  File "/home/abuild/rpmbuild/BUILD/pykeepass-3.0.3/pykeepass/kdbx_parsing/common.py", line 326, in <module>
    'chacha20': b'\xd6\x03\x8a+\x8boL\xb5\xa5$3\x9a1\xdb\xb5\x9a'
TypeError: __init__() missing 1 required positional argument: 'encoding'`

Python 2 trace:
`Python 2.7.14 (default, Oct 12 2017, 15:50:02) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykeepass import PyKeePass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass
  File "pykeepass/pykeepass.py", line 15, in <module>
    from pykeepass.kdbx_parsing.kdbx import KDBX
  File "pykeepass/kdbx_parsing/__init__.py", line 1, in <module>
    from .kdbx import KDBX
  File "pykeepass/kdbx_parsing/kdbx.py", line 2, in <module>
    from .kdbx3 import DynamicHeader as DynamicHeader3
  File "pykeepass/kdbx_parsing/kdbx3.py", line 10, in <module>
    from .common import (
  File "pykeepass/kdbx_parsing/common.py", line 326, in <module>
    'chacha20': b'\xd6\x03\x8a+\x8boL\xb5\xa5$3\x9a1\xdb\xb5\x9a'
TypeError: __init__() takes at least 4 arguments (3 given)`

**Comment by cap44** [comment]
@Evidlo I've posted the stack traces for Python 3 & Python 2 - see above comment

**Comment by Evidlo** [comment]
What version of `construct` are you on?

This is weird because `Mapping.__init__` only takes 3 arguments, none of which are `encoding`: https://github.com/construct/construct/blob/master/construct/core.py#L1890

**Comment by cap44** [comment]
@Evidlo the version of `python-construct` that comes with openSUSE 15.1 is somewhat old: 2.8.12

**Comment by Evidlo** [comment]
Well that's the problem then.  I'm not familiar with OpenSUSE packaging, so I'm not sure what your options are.  Maybe you could package construct yourself?

**Comment by Evidlo** [comment]
Seems to be an openSUSE problem.  If not, I can reopen.
