### ISSUE TITLE
extreme slow KDBX4 AES loading

### ISSUE THREAD

**Issue by okias** [libkeepass/pykeepass#168]
#167 after KDBX4 fix, these files loads, but it takes too long.

**Comment by okias** [comment]
trying upload pstats and visualization of profiling process to github UI, but no success :( I'll try later..

**Comment by Evidlo** [comment]
This is a known issue.  Its because the key has to pass through CFFI to the
low level code in cryptodome for every round.  Just use argon2 instead of
AESKDF.

**Comment by okias** [comment]
maybe do performance part of code in rustlang? I'm not skilled enough to do this, just thought.

**Comment by Evidlo** [comment]
Not sure if it's worth fixing this.  AESKDF is a weird key derivation algorithm invented by the KeePass author for KeePass 1.  I don't think it's recommended anymore.

**Comment by Evidlo** [comment]
Closing this for now.  I don't think it's worth adding native extensions to this project just to get AESKDF faster.
