### ISSUE TITLE
Incorrect credentials exception

### ISSUE THREAD

**Issue by mgoral** [libkeepass/pykeepass#173]
Hi,

whenever pykeepass fails to open a database because of incorrect credentials (wrong password, wrong keyfile or both) it raises `construct.core.ChecksumError`. It's hard to catch because:

1. it's exception from a library used internally by pykeepass; by importing it I'd have to declare it as a direct dependency of my program, which feels wrong
2. it doesn't say that it actually is caused by incorrect credentials - my guess is that invalid (e.g. incorrectly copied) database could fail checksum verification as well.

Is it possible for pykeepass to somehow handle this exception and establish some kind of interface which would unambiguously inform about database decryption failure? Re-raising custom exception would be fine for me (e.g.  `pykeepass.CredentialsError`, which is defined, but its usage is commented-out in kdbx[3,4].py) .

**Comment by Evidlo** [comment]
> it doesn't say that it actually is caused by incorrect credentials - my guess is that invalid (e.g. incorrectly copied) database could fail checksum verification as well.

I tried filing an issue about this a while ago, but it was closed for some reason: https://github.com/construct/construct/issues/731

At the very least, we could have an internal exception which covers auth failure and integrity checksum failure.

**Comment by mgoral** [comment]
I think I get it. In that case re-raising that exception as internal one sounds reasonable to me. Too bad construct's author didn't like your idea of runtime exceptions. I used similar concept previously for hand-made validators in other projects and they always worked pretty great.

**Comment by Evidlo** [comment]
I made an `exception` branch which raises a `CredentialsIntegrityError`.  Let me know what you think.

**Comment by mgoral** [comment]
I can't test it right now, but just looking at the code it seems that it'll do exactly as we spoke, so that's great. Thanks! :+1:

**Comment by mgoral** [comment]
One question though: I see that last official release was in February 2018 so do you plan to eventually release this and possibly other changes?

**Comment by Evidlo** [comment]
If you mean release on pypi, I'm not currently a maintainer there: https://github.com/libkeepass/pykeepass/issues/100

**Comment by Evidlo** [comment]
Fixed in release 3.1.1
