### ISSUE TITLE
entry.history

### ISSUE THREAD

**Issue by BoomerB** [libkeepass/pykeepass#174]
Hi,
I'm working on some tests for the history feature
now I noticed different behavior for entries in the test files and entries created by pykeepass
the entries in the test files always return a list, e.g. when the entry has no history it returns an empty list
entries created by pykeepass return None when there's no history because there's no "History" tag in the XML data
I assume the test files were created by the original KeePass for maximum compatibility.
So, now the question is: is this deviation acceptable? or should we change the behavior of pykeepass?
Kind regards
Boomer

**Comment by Evidlo** [comment]
Are you referring to `Entry.history`?  If so, I think it should return an empty list when there are no history items, regardless of the XML.

**Comment by BoomerB** [comment]
ok, this is easy
