### ISSUE TITLE
Unable to access uncompressed attachments

### ISSUE THREAD

**Issue by roddhjav** [libkeepass/pykeepass#181]
Hi,

When a database is created with no compression settings, pykeepass fails to read the attachments. See the related issue in pass-import: https://github.com/roddhjav/pass-import/issues/90#issuecomment-552216409

Example of the issue with a DB without compression:
```python
>>> from pykeepass import PyKeePass
>>> 
>>> keepass = PyKeePass('database.kdbx', password='password')
>>> for kpentry in keepass.entries:
...     for att in kpentry.attachments:
...             print(att.filename)
...             print(att.data)
file.txt
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/pykeepass/attachment.py", line 45, in binary
    return self._kp.binaries[self.id]
  File "/home/user/.local/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 479, in binaries
    if elem.attrib['Compressed'] == 'True':
  File "src/lxml/etree.pyx", line 2478, in lxml.etree._Attrib.__getitem__
KeyError: 'Compressed'
```

**Comment by Araly** [comment]
so, how do export with compression ?

**Comment by Evidlo** [comment]
I just created a `compressed_fix` branch.  Let me know if it works for you.

**Comment by roddhjav** [comment]
That works. Thank for the quick fix.

**Comment by Araly** [comment]
how would I test or use this branch ? I cloned it but then I don't know what to do. I'm trying to have pass-import use it.

**Comment by roddhjav** [comment]
In your cloned directory simply run: `pip install . --user` and you should be able to use pass-import with this branch.
