### ISSUE TITLE
[FR] search with tag

### ISSUE THREAD

**Issue by fazlerabbi37** [libkeepass/pykeepass#182]
It would be great if searching entries by tag was added. It would make bulk edit and management easier.

**Comment by Evidlo** [comment]
What exactly do you mean by 'tag'?

**Comment by fazlerabbi37** [comment]
> What exactly do you mean by 'tag'?

In the Keepass 2.43, if you go to Entry>Properties you would be able to see the Tags input field. It takes comma separated string as input and each separated value creates a new tag if it already doesn't exist. 

It can be used from Find (Ctrl+f) or from Find>Tag>Select a Tag.

**Comment by Evidlo** [comment]
See the most recent commit on master and tell me how it looks.

**Comment by fazlerabbi37** [comment]
> See the most recent commit on master and tell me how it looks.

I just checked it and it works! Thank you very much!
