### ISSUE TITLE
Feature request: Password Generation

### ISSUE THREAD

**Issue by d0peman** [libkeepass/pykeepass#184]
The ability to generate *truly random* passwords using various character sets of the user's choosing would be a very useful feature. (A-Z, a-z, 0-9, Special Chars, potentially other special characters that are present within KeePass by default).

Currently can't even see a way to change the password of an entry manually though honestly. Hope I'm not just being silly

**Comment by Evidlo** [comment]
> Currently can't even see a way to change the password of an entry manually though honestly.

Just set `entry.password` to whatever you want and save the database.

Password generation is outside the scope of this library.  There are many password generation libraries available on PyPi and it's best that we not duplicate their efforts:

- https://github.com/suryasr007/random-password-generator
- https://github.com/atsmin/passiter

**Comment by d0peman** [comment]
> Just set `entry.password` to whatever you want and save the database.

Ah, thank you. Genuinely feel so stupid right now.

> Password generation is outside the scope of this library.

OK, that's fair enough. Just felt like it would be a nice little addition to the library but I appreciate your help either way. Great work on this amazing library, man!
