### ISSUE TITLE
Wide unicode chars break regex on Windows

### ISSUE THREAD

**Issue by monomon** [libkeepass/pykeepass#190]
https://github.com/libkeepass/pykeepass/blob/fd290bf5218e65c043eeba6860bc07434dc1119c/pykeepass/kdbx_parsing/common.py#L193

On python without wide unicode support, throws error "bad character range".

The stackoverflow thread linked in the code shows that this change breaks for all "narrow builds" of Python, which is all default builds on Windows, Mac.

Perhaps there should be a condition in the code and not test the extra characters if they are not supported.

This breaks with Python 2.7.17 (latest available 2.7 build), but does work on 3.8.1.
Unfortunately some industries are still stuck with 2.7 until several major players move on...

Edit: After some research, it seems this is a [deep and contested problem](https://bugs.python.org/issue12729) with narrow python and the re module. Still, since there is already a whitelist of the characters we want to pass through, a positive filter would be better, and could avoid using re for this altogether (possibly with a performance benefit).
Let me put together a pr and see what you think.

**Comment by Evidlo** [comment]
Is there a PR forthcoming or should I close this issue?

**Comment by MoisMoshev** [comment]
apologies for the delay, here it is
https://github.com/libkeepass/pykeepass/pull/209

**Comment by Evidlo** [comment]
I just tested with Python 3.8 installed from python.org's installer on Windows 10.  It seems like wide unicode support is enabled, and I'm able to open a database just fine.

**Comment by MoisMoshev** [comment]
Indeed I think this is only a problem on Python 2.7.

**Comment by Evidlo** [comment]
Ok, the branch is there if you need it.  I think you can always put a direct link to the branch in your setup.py.

https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repository-as-a-dependency

**Comment by MoisMoshev** [comment]
Great, thank you!
We are actually using devpi to distribute packages in our local network, and I think just uploading the specific version and reinstalling it works, even though it is not tagged.
