### ISSUE TITLE
How to read a subtree?

### ISSUE THREAD

**Issue by duhlig** [libkeepass/pykeepass#196]
Silly question, sorry: How to read in a whole subtree of the KDB into a python dict? The leaves shall consist of key = username and value = password. The group structure between the one I queried for and the leaves shall be taken over.

Kind regards, Dietmar

**Comment by Evidlo** [comment]
Sorry I missed seeing this issue.

I'm not sure exactly what dict structure you're looking for, but if you recursively iterate groups and entries you can build up a tree structure.

``` python
def iterate_group(group):
    branch = {}
    for e in group.entries:
        branch[e.username] = e.password
    for g in group.groups:
        branch[g.title] = iterate_group(g)
    return branch

tree = iterate_group(kp.root_group)
```

I haven't tested this.

**Comment by duhlig** [comment]
Thanks for the hint. Your example looks elegant. I tried it but it gives me an error:

```
>>> kp.root_group
Group: "/"
>>> kp.groups
[Group: "/", Group: "color/", Group: "color/light/", Group: "Recycle Bin/"]
>>> tree = iterate_group(kp.root_group)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in iterate_group
AttributeError: 'Group' object has no attribute 'groups'
>>> g = kp.groups[1]
>>> g
Group: "color/"
>>> g.entries
[]
>>> g.groups
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Group' object has no attribute 'groups'
```

Did I anything wrong?

**Comment by Evidlo** [comment]
I updated the example.  It should work now.

**Comment by duhlig** [comment]
Thank you, it works. This helps me to get a much simpler solution than now.
