### ISSUE TITLE
Cannot create PyKeePass object

### ISSUE THREAD

**Issue by Kruskin** [libkeepass/pykeepass#198]
```python
from pykeepass import PyKeePass

kp = PyKeePass('testdb.kdbx', keyfile='test.key')
# tried the alternative below after changing the testdb master password
# kp = PyKeePass('testdb.kdbx', password='test')

# any code below, like print('weee') does not execute
```

I'm inexperienced, but running debug showed a constant loop through the parsing process. I tried both with setting path and with placing the db and key into the project directory. Script loops infinitely until I stop it which then exits with code -1. Manually entering the password or using the keyfile worked. 
`

**Comment by Kruskin** [comment]
I reduced the db key-transformation iterations to the default 1s and the object was created in a minute. Reverted back to my prior settings and let the script run, and it finally worked in just under 8 minutes.

I suppose that is working as intended then. For my own education though, can someone please explain to me why PyKeePass takes so much longer to open the db than when using KeePass normally?

**Comment by Evidlo** [comment]
Sounds like you're using aeskdf.

https://github.com/libkeepass/pykeepass/issues/168

**Comment by Kruskin** [comment]
That is correct. I only now just realized, because of your link, that by default github only shows Open issues or I would have found that a long time ago. Thanks!
