### ISSUE TITLE
compatibility issue with 3rd party tool

### ISSUE THREAD

**Issue by devstek** [libkeepass/pykeepass#211]
Hi all,

thanks for providing this great library. 
At the moment i'm facing an issue with a third party tool called **[kpcli](https://sourceforge.net/projects/kpcli/)**. This tool is used for programmatic access to the generated keepass file. But in the tool i get only the the output (File is secured by key File without password) with a hash ref value:

```
kpcli-3.6:/> open keepass_minimal.kdbx passwords.key 
Provide the master password: *************************
kpcli-3.6:/> show /passwords/Title

 Path: /passwords/
Title: Title
Uname: Username
 Pass: HASH(0xef34a8) 
  URL: 
Notes: 
```

So it seems that there is only some reference to hash (it's a perl tool) is shown. the keepass file is full readable through keepassxc and values are shown correctly. **Also after editing the keepassfile in keepassxc the password values are readable  again for kpcli.**

**Steps to reproduce:**
* I have a blank keepassfile. Version 3.1 with aes. 
* I will put entries in keepassfile with the following code
````
from pykeepass import PyKeePass, create_database

kp = PyKeePass('keepass_minimal.kdbx', password=None, keyfile='passwords.key')
kp.add_entry(kp.root_group, "Title", "Username", "Passw0rd")
kp.save()
````
* open saved generated keepassfile in kpcli
```
bash-4.2# ./kpcli-3.6.pl keepass_minimal.kdbx 

KeePass CLI (kpcli-3.6) v3.6 is ready for operation.
Type 'help' for a description of available commands.
Type 'help <command>' for details on individual commands.

kpcli-3.6:/> open keepass_minimal.kdbx passwords.key 
Provide the master password: *************************
kpcli-3.6:/> show passwords/Title

 Path: /passwords/
Title: Title
Uname: Username
 Pass: HASH(0x1f22e68)
  URL: 
Notes: 
```
* edit keepass file in keepassxc (password is shown) and add a note or so
* open in kpcli again
```
kpcli-3.6:/> open keepass_minimal.kdbx passwords.key 
Provide the master password: *************************
kpcli-3.6:/> show passwords/Title

 Path: /passwords/
Title: Title
Uname: Username
 Pass: Passw0rd
  URL: 
Notes: 123
```

[passwords.txt](https://github.com/libkeepass/pykeepass/files/5585578/passwords.txt)
[keepass_minimal.txt](https://github.com/libkeepass/pykeepass/files/5585581/keepass_minimal.txt)

**

**Comment by Evidlo** [comment]
Thanks for the details.  Can you try out the `protectedfix` branch?  The issue should be fixed now.

**Comment by devstek** [comment]
Great News! I've tested it with your branch. And it seems to work! Thank you! 
Is there any date, when this branch will merged to master for new pip release version?

**Comment by Evidlo** [comment]
Maybe another week or two.
