### ISSUE TITLE
Drop Python2 support

### ISSUE THREAD

**Issue by pschmitt** [libkeepass/pykeepass#214]
We really should drop Python 2.7 support. It's dead already.

https://www.python.org/doc/sunset-python-2/

**Comment by Evidlo** [comment]
I think we should hold off until the next time we run into a python2/3 compatibility problem or do a refactor.  I haven't noticed any extra work overhead from python2.

**Comment by pschmitt** [comment]
I don't believe that keeping compatibility for an EOL piece of software until there's an issue with it is the right thing to do. And the old releases will not be going anywhere. Py2k users can still use those.

Also we won't be able to make use of any modern tools like Poetry with it (see #215)

**Comment by Evidlo** [comment]
Who says poetry doesn't support python2?

**Comment by pschmitt** [comment]
Right. It does, point taken. I expected it not to. I'm wrong. Nevertheless python 2 and the version pinning that comes with it should be removed. It's just eol. Even pip will stop releasing py2k versions at some point. For a project like pykeepass - that manages passwords - it's just wrong in my opinion to still support a programming language that no longer receives security fixes.

**Comment by hugovk** [comment]
> Even pip will stop releasing py2k versions at some point.

pip is dropping support in pip 21.0, due next month:

* https://github.com/pypa/pip/issues/6148

And when run on Python 2.7 has been showing this warning:

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**Comment by Evidlo** [comment]
At the very least I want to merge `protectedfix`, `pathfix` and any other pending changes into one last release supporting 2.7.

**Comment by pschmitt** [comment]
Sure, why not.

**Comment by MoisMoshev** [comment]
The tests are failing (and some error with parsing the test database) when run with Python 3.8. Tried merging protectedfix and pathfix but it did not help.
Are there other branches that are needed?

**Comment by pschmitt** [comment]
contruct dropped python 2 support as well

#242

https://github.com/construct/construct/commit/52c7cd23933d83922a289112a7c01dad7ffde5a3

**Comment by Evidlo** [comment]
This was done in 4.0.1
