### ISSUE TITLE
No "Save as" use case documentation

### ISSUE THREAD

**Issue by basak** [libkeepass/pykeepass#220]
Hi,

Thank you for pykeepass!

I'd like to open a database, make some changes, then save it under a different filename. I could copy the file first (eg. with `shutil.copyfile`), but an explicit `save_as()` method on the `PyKeePass` object would be nice. Alternatively, looking at the code, I could trivially modify the `filename` attribute, but that might interfere with a solution to #219 so I avoided that. It'd be great to have some explicit, supported, documented way of doing this.

Thanks!

**Comment by Evidlo** [comment]
save() accepts an argument

**Comment by basak** [comment]
Sorry, I forgot some of the details I had in mind when I wrote up the issue, so i wasn't clear. `save()` with a `filename` argument doesn't look like it'll change the `filename` attribute. So the `PyKeePass` instance will still be associated with the original filename. In my case, that's dangerous because I'll have removed entries and really don't want to accidentally modify the original database. So I want the `PyKeePass` instance to end up associated with the new filename only, with no remaining references to the old name.

Looking at the code, I could modify the `filename` attribute directly and this would work today, but it isn't clear if this is part of the API that this will disassociate the old name, or if it might break in future. So what I'm requesting is more a specific API-specified method to _disassociate_ with an old filename that I no longer want to touch.

**Comment by Evidlo** [comment]
Setting `kp.filename` is the intended way to do this.

Writing up proper Sphinx documentation is on the todo list which should clear this up in the future.

**Comment by basak** [comment]
Great, thanks! I guess that reduces this issue to just a documentation request then.
