### ISSUE TITLE
Backward compatibility with KDBX 3.1?

### ISSUE THREAD

**Issue by robertvazan** [libkeepass/pykeepass#224]
After recent upgrade, pykeepass produces KDBX 4 files, which are not supported by all the other KDBX-reading libraries and tools I use. Would it be possible to support writing of KDBX 3.1 files? As I understand it, KDBX 3.1 support is still in the code. It's just not exposed in the API. Would it be possible to expose it as a parameter on `create_database` or `save`?

**Comment by Evidlo** [comment]
pykeepass saves in the same version as the file was opened.  It actually doesn't support converting between versions yet.

For now, just make a blank KDBX3 file in keepassxc and ship that with your application if you need to create new databases.

**Comment by robertvazan** [comment]
I didn't know about this workaround. It will do. Thanks.
