### ISSUE TITLE
Python newbie can't create database

### ISSUE THREAD

**Issue by symcbean** [libkeepass/pykeepass#225]
(I'm a newbie with Python - apologies of the answer to this is really obvious).

I want to create a KeePass database (from a CSV datafile and command line options) but I'm unable to invoke the create_database() method - the examples in the docs don't show how to do this. I tried....
```
import sys
import argparse
import csv
from pykeepass import PyKeePass

args = readCmdLine()
kpx =  PyKeePass.create_database (args.file, args.pasphrase)
```
but I get....
```
$ cat ../testpy.csv | python generator.py -p letmein -f test1.kdbx
Traceback (most recent call last):
  File "generator.py", line 21, in <module>
    kpx =  PyKeePass.create_database (args.file, args.pasphrase)
AttributeError: type object 'PyKeePass' has no attribute 'create_database'
```

Help!

I also tried....
```
kpx =  create_database (args.file, args.pasphrase)
NameError: name 'create_database' is not defined
```
and
```
kpx =  pykeepass.create_database (args.file, args.pasphrase)
NameError: name 'pykeepass' is not defined
```

**Comment by jugmac00** [comment]
`create_database` is not a member of the class PyKeepass but from the pykeepass module

https://github.com/libkeepass/pykeepass/blob/8a41d9b4b1e30cf98b1d56e26350208293b37c78/pykeepass/pykeepass.py#L680

Try a

`from pykeepass import create_database`

**Comment by jugmac00** [comment]
PS I am my mobile. I'll give a more thorough explanation tomorrow.

**Comment by symcbean** [comment]
Got it - and can now create a database - and understand how 'import' works a bit better.
Ta

**Comment by jugmac00** [comment]
Glad to hear!

As a minor addition... 

When you write `from pykeepass import create_database`,  `pykeepass`  does not refer to the module, although `create_database` is defined there, but to the `pykeepass` package.

The (installed) `pykeepass` package has a public API, which offers what you may import.

This is defined in 
https://github.com/libkeepass/pykeepass/blob/8a41d9b4b1e30cf98b1d56e26350208293b37c78/pykeepass/__init__.py#L1-L4

`public API` means, that you, as a user of the library, can rely on this interface. It should be fairly stable and usable for the forseeable future.

You certainly also could import `create_database` as follows...

`from pykeepass.pykeepass import create_database` where the first pykeepass refers to the package, the second to the module (file).

But this is not recommended, as this could change for several reasons, ie. internal restructuring, renaming, using a src-layout for packaging...

That all said, maybe it is a good idea to add some documentation on how to create a new database?

@symcbean This is a great opportunity to give back to the developers of this library, and this could help future users.
