### ISSUE TITLE
Malformed timestamp?

### ISSUE THREAD

**Issue by robertvazan** [libkeepass/pykeepass#226]
Another KDBX implementation is [erroring out on file generated by pykeepass](https://github.com/jorabin/KeePassJava2/issues/27). It looks like pykeepass generated timestamp `2021-01-02T03:31:49.386013+00:00` while original KeePass only generates timestamps that match format `yyyy-MM-dd'T'HH:mm:ss'Z'`. This looks like format extension in pykeepass that is not handled well by other implementations.

The offending entry was actually copied (via pykeepass API) from another file created by KeePassX. I am mentioning this just in case it has any effect on timestamp formatting.

**Comment by Evidlo** [comment]
I added a fix in the datetime branch, although I'm not sure if it really should be merged yet.

**Comment by Evidlo** [comment]
Seems like this will probably be fixed in KeePassJava2.  If it turns out there are other tools which depend on dates being formatted in a specific ISO8601 variant, we can look into changing the format emitted by pykeepass.
