### ISSUE TITLE
implement touch for groups

### ISSUE THREAD

**Issue by A6GibKm** [libkeepass/pykeepass#234]
Entries have a function touch() to update their accessed & modified dates. Groups also have atime & ctime but they do not have such function.

**Comment by A6GibKm** [comment]
Is it Ok that touch is defined now both in base element and entry? I don't know if that could lead to a conflict.

**Comment by Evidlo** [comment]
Fixed in https://github.com/libkeepass/pykeepass/commit/74086581cb671558263bee360c96a2f82e3a52f3
