### ISSUE TITLE
Adhere to SemVer for versioning/changes

### ISSUE THREAD

**Issue by stephen-dexda** [libkeepass/pykeepass#235]
I'm not sure whether it's currently intended that pykeepass versions follow SemVer, but would be great if they did.

I noticed that e.g. 3.2.1 has at least one API change vs. 3.2.0 - an incorrect DB password now raises `pykeepass.exceptions.CredentialsError` instead of `pykeepass.exceptions.CredentialsIntegrityError`, which breaks exception handling for packages with dependency specifications such as `pykeepass~=3.2`.

**Comment by pschmitt** [comment]
I'm no SemVer expert but IMHO this kind of change (an exception **type**) does not warrant a minor version upgrade. If 3.2.0 didn't raise any kind of exception then yes. School me.

**Comment by stephen-dexda** [comment]
From https://semver.org/:

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY also include minor and patch level changes.

Exceptions raised by a public method/function in a module are part of its API, so the above would apply.

A concrete example to illustrate the problem:

Code:

```python
try:
    return pykeepass.PyKeePass(db_path, password=db_password)
except pykeepass.exceptions.CredentialsIntegrityError as exc:
    # Handle incorrect password.
```

Project dependency spec.:

```toml
pykeepass~=3.2
```

A dependency spec. of `<pkg>~=<major>.<minor>` is a [compatible release clause](https://www.python.org/dev/peps/pep-0440/#compatible-release):

> A compatible release clause consists of the compatible release operator ~= and a version identifier. It matches any candidate version that is expected to be compatible with the specified version.

With the above dependency spec., when 3.2.0 was the latest release, 3.2.0 would be installed per the dependency spec., and an incorrect password would throw a `pykeepass.exceptions.CredentialsIntegrityError` exception, which would be handled properly by the above code.

Now that 3.2.1 has been released, 3.2.1 would be installed per the dependency spec., and an incorrect password instead throws a `pykeepass.exceptions.CredentialsError`, breaking the above code.

**Comment by pschmitt** [comment]
I understand and have to admit that you seem to be right.

We never officially committed to semantic versioning (please correct me if I'm wrong @Evidlo). Maybe we should pay closer attention to this in the future.

Sidenote: This issue once again highlights the fact that dependency locking is important. You wouldn't have been bitten by this if you explicitly depended on `3.2.0` instead of `3.2`.

**Comment by stephen-dexda** [comment]
> You wouldn't have been bitten by this if you explicitly depended on 3.2.0 instead of 3.2.

Sure, but there are a couple of problems with this:

* Pinning to 3.2.0 would have meant not benefitting from bug fixes, e.g.:

> fixed #193 - kp.groups, kp.entries not returning elements with name/title None

* It assumes the use of e.g. PyPI as a dependency source, where arbitrarily old versions might still be available. This doesn't work for e.g. distro packages (DEB, RPM etc.). It could be argued that downstream packagers should definitively determine the software's versioning policy, but that's not always going to happen.

In my case the breakage was caught at the testing stage in any case and freezing dependencies happens elsewhere (at a containerisation stage).

**Comment by Evidlo** [comment]
Sure, we can be more mindful of this in the future.

**Comment by stephen-dexda** [comment]
Can I suggest adding a versioning policy or statement of intent somewhere (e.g. README.rst, CONTRIBUTING.rst), even if it's just "we generally aim to follow SemVer, but this is not guaranteed at present".

**Comment by Evidlo** [comment]
It was just an oversight, so I don't think that's necessary.

**Comment by stephen-dexda** [comment]
It would take away the guesswork for pykeepass consumers (users, distro packagers etc.) as far as what to expect in compatibility terms, and (future) contributors as far as how to bump the version for a given type of change.

Could also be just "versioning should follow SemVer" or "we don't have a strict versioning policy at present".

**Comment by Evidlo** [comment]
> Could also be just "versioning should follow SemVer" or "we don't have a strict versioning policy at present".

I can't recall ever seeing another Python project do this before.  But again, I'll be more mindful of SemVer when making releases.
