### ISSUE TITLE
Keepass field references not working

### ISSUE THREAD

**Issue by elmir-b** [libkeepass/pykeepass#247]
Keepass allows field references in usernames and passwords. From https://keepass.info/help/base/fieldrefs.html

`KeePass can insert data stored in different entries into fields of an entry. This means that multiple entries can share a common field (user name, password, ...), and by changing the actual data entry, all other entries will also use the new value.`

pykeepass reads the reference text and NOT the actual reference value.

**Comment by Evidlo** [comment]
https://github.com/libkeepass/pykeepass/pull/178

Seems documentation still needs to be added.

**Comment by elmir-b** [comment]
@Evidlo thank you. I will close this issue then.
