### ISSUE TITLE
Entries without a title throw an error

### ISSUE THREAD

**Issue by krey** [libkeepass/pykeepass#259]
From https://github.com/libkeepass/pykeepass/blob/master/pykeepass/entry.py#L79
```python
def _get_string_field(self, key):
    field = self._xpath('String/Key[text()="{}"]/../Value'.format(key), first=True)
    if field is not None:
        return field.text
```

Running this on an entry with an empty title results in `etree.tostring(field) == b'<Value/>'` and `field.text is None`.

You can no longer run things like `kp.entries` because it will throw when trying to join `None` to the end of the path

```python
~/miniconda3/envs/main/lib/python3.8/site-packages/pykeepass/entry.py in __str__(self)
    292 
    293     def __str__(self):
--> 294         pathstr = '/'.join(self.path)
    295         if self.is_a_history_entry:
    296             return '[History of: {}]'.format(pathstr)

TypeError: sequence item 1: expected str instance, NoneType found
```

Would it be safe to change `_get_string_field` to

```python
    if field is not None:
        if field.text is not None:
            return field.text
        else:
            return ''
```
?

**Comment by Evidlo** [comment]
`Entry.__str__` looks like this now:

``` python
def __str__(self):
    # filter out NoneTypes and join into string
    pathstr = '/'.join('' if p==None else p for p in self.path)
    if self.is_a_history_entry:
        return '[History of: {}]'.format(pathstr)
    return 'Entry: "{} ({})"'.format(pathstr, self.username)
```

Are you using the most recent version?

https://github.com/libkeepass/pykeepass/commit/98b323e257897eac3978397d19b19ec43ced053e

**Comment by Evidlo** [comment]
I just released version 4.0.1 which has the mentioned change.

**Comment by krey** [comment]
Thanks very much - latest release works great

**Comment by krey** [comment]
Thanks for the updated release.

I run into a sneaky conversion from `""` to `None`.

```python
kp = pykeepass.PyKeePass('test.kdbx', password='test')
kp.add_entry(kp.root_group, 'gmail', '', 'myPassw0rdXX')
kp.save()
kp.reload()
print(kp.entries[0].username) # prints None
```

I'm guessing the db isn't able to distinguish a missing field from a field with empty value?
