### ISSUE TITLE
Implement a setter for history

### ISSUE THREAD

**Issue by A6GibKm** [libkeepass/pykeepass#264]
I want to implement a slim version of history in password safe (https://gitlab.gnome.org/World/PasswordSafe/-/merge_requests/514) and a blocker is not having a way to remove an entry from the history, having either a setter or a `entry.remove_from_history(history_entry)` method would solve this.

**Comment by Evidlo** [comment]
I added a `delete_history` function on master.  Can you try it out?

**Comment by Evidlo** [comment]
I didn't see that you were working on your own implementation.  Sorry about that.

**Comment by A6GibKm** [comment]
Don't worry. This is what I up came with. I am not familiarized enough with how the library handles errors.

```python
    def remove_from_history(self, entry):
        '''
        Remove the entry from self's history
        '''
        if entry.is_a_history_entry:
            hist = self._element.find('History')
            if hist is not None:
                self._element.find('History').remove(entry._element)
```

And it worked with password safe. Tested master, and it seems to do the job with the added benefit of being a clean implementation. Thanks.
