### ISSUE TITLE
Duplicate error in the function that writes data to the keepass database

### ISSUE THREAD

**Issue by ShellAndPython** [libkeepass/pykeepass#273]
I'm facing an error issue in an implementation. The logic would be to read a CSV file, prepare the data and send it to the add_entry() method.
But what happens is that executing the reading in the same file several times, the add_entry() method is sometimes not able to identify that an entry already exists inside the database and ends up inserting this information, causing duplication.

**Comment by Evidlo** [comment]
Bump

**Comment by ShellAndPython** [comment]
Fogot this .. sorry guys
