### ISSUE TITLE
Field replacement does not work

### ISSUE THREAD

**Issue by joelroyer** [libkeepass/pykeepass#282]
Field replacement does not work.
I try to replace the fields in the url but it fails.

Here is the code :
```
from pykeepass import PyKeePass²
kp = PyKeePass('Tests.kdbx', 'test')
group = kp.find_groups(uuid=uuid.UUID('6bfbcbc0d6ef4196812b013d8274ad39'), first=True)
for entry in group.entries:
    print(entry.username + ";" + entry.url)
```

Here is the result :
```
toto;http://localhost:8888/auth?username={username}&password={password}
```

Expected :
```
toto;http://localhost:8888/auth?username=toto&password=azerty123
```

Can't join Tests.kbdx but you can download it here : https://we.tl/t-vDKp041sHF

**Comment by pschmitt** [comment]
This isn't a pykeepass issue.
To format strings in Python do the following:

```python
s = "toto;http://localhost:8888/auth?username={username}&password={password}"
s.format(username="toto", password="mypassword01")
```

More concretely in your example this would be:

```python
from pykeepass import PyKeePass
kp = PyKeePass('Tests.kdbx', 'test')
group = kp.find_groups(uuid=uuid.UUID('6bfbcbc0d6ef4196812b013d8274ad39'), first=True)
for entry in group.entries:
    print(entry.username + ";" + entry.url.format(username=entry.username, password=entry.password))
```

Another tip: Read up on [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings) -> `print(f"{entry.url.format(username=entry.username, password=entry.password)}")`
