### ISSUE TITLE
Bug and DB corruption

### ISSUE THREAD

**Issue by jzielke84** [libkeepass/pykeepass#301]
When creating multiple entries for each host the module throws the following error:
`json
 stream read less than specified amount, expected 254480, found 717
fatal: [acdtst-09]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/yc/t7s_9d0x2hj0pl7v300pr40r0000gn/T/ansible_keepass_payload_1dbsqm5z/ansible_keepass_payload.zip/ansible/modules/keepass.py\", line 262, in <module>\n  File \"/var/folders/yc/t7s_9d0x2hj0pl7v300pr40r0000gn/T/ansible_keepass_payload_1dbsqm5z/ansible_keepass_payload.zip/ansible/modules/keepass.py\", line 187, in main\n  File \"/usr/local/lib/python3.9/site-packages/pykeepass/pykeepass.py\", line 65, in __init__\n    self.read(\n  File \"/usr/local/lib/python3.9/site-packages/pykeepass/pykeepass.py\", line 103, in read\n    self.kdbx = KDBX.parse_file(\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 309, in parse_file\n    return self.parse_stream(f, **contextkw)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 300, in parse_stream\n    return self._parsereport(stream, context, \"(parsing)\")\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 1982, in _parse\n    subobj = sc._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 2440, in _parse\n    return self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 3628, in _parse\n    return sc._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 1982, in _parse\n    subobj = sc._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 2440, in _parse\n    return self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 697, in _parse\n    obj = self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 3558, in _parse\n    return sc._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 697, in _parse\n    obj = self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 3628, in _parse\n    return sc._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 697, in _parse\n    obj = self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 697, in _parse\n    obj = self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 2362, in _parse\n    e = self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 1982, in _parse\n    subobj = sc._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 2440, in _parse\n    return self.subcon._parsereport(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 312, in _parsereport\n    obj = self._parse(stream, context, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 4374, in _parse\n    data = stream_read(stream, length, path)\n  File \"/usr/local/lib/python3.9/site-packages/construct/core.py\", line 92, in stream_read\n    raise StreamError(\"stream read less than specified amount, expected %d, found %d\" % (length, len(data)), path=path)\nconstruct.core.StreamError: Error in path (parsing) -> body -> payload -> block_data\nstream read less than specified amount, expected 254480, found 717\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

**After some retires this even resulted in a database corruption (error INNER HEADER-ID).**

**Comment by Evidlo** [comment]
If you could provide some sample code to recreate this corruption, that would be helpful.  Otherwise, there's not a whole lot I can do.

**Comment by Evidlo** [comment]
Or a sample database I can open.
