### ISSUE TITLE
Very slow loading database with high number of iterations

### ISSUE THREAD

**Issue by meichthys** [libkeepass/pykeepass#303]
When the database iterations are set to a large value like 10,000,000, loading the database takes over a minute.
```
# load database
>>> kp = PyKeePass('db.kdbx', password='somePassw0rd')
```

If this is expected/normal, please feel free to close this issue. I just wanted to document it for future reference.

Reducing the iterations to 500,000 reduces the time to load to about 2 seconds.

**Comment by Evidlo** [comment]
Yes this is a known issue: https://github.com/libkeepass/pykeepass/issues/168

I recommend switching your KDF algorithm from AESKDF to argon2.
