### ISSUE TITLE
find_entries chokes when explicit parameters have a None value

### ISSUE THREAD

**Issue by rtl19** [libkeepass/pykeepass#308]
I assumed when using the find_entries search method that if I pass in a parameter with a value of None that it would not be used for the actual search.  I made that assumption based on the documentation that indicates something like 'username=None' is its value when not explicitly specified in the method call.  However, I'm seeing different results between the following:
```
find_entries(title='my title', username=None)
vs
find_entries(title='my title')
```
Am I misunderstanding the documentation?

**Comment by Evidlo** [comment]
Nope, that's a bug.  I've just fixed it on master.

https://github.com/libkeepass/pykeepass/commit/ec099e94f79824a550852bdbd2c08a8377ac35ad
