### ISSUE TITLE
hide/mask the master password

### ISSUE THREAD

**Issue by azinsharaf** [libkeepass/pykeepass#310]
Hi, 
I'm wondering how I can encrypt the master password. Let me explain the scenario. I have published a web service (written in python) that connects to our company's KeePass file (using `pykeepass`) and gets some accounts password to do some tasks. The master password is exposed in the `.py` file.

`kp = PyKeePass('db.kdbx', password='exposed_pw')`

I am not sure what the best way is to hide/encrypt the master password. Can pykeepass or any other library do it? What is the best practices in these cases? 
My goals is if users open the `py` file they can't see/use the master pw.

**Comment by Evidlo** [comment]
I don't fully understand the scenario.  Why do the users have access to the .py file if it's a web service?

**Comment by azinsharaf** [comment]
That is true. Users don't have access to the py file since they use the web service. But the script exists in our Git repository and also in our company's web server. Server access is restricted but i still think there could be a better way to use the master key password instead of hard coding it in the code.

**Comment by jugmac00** [comment]
> That is true. Users don't have access to the py file since they use the web service. But the script exists in our Git repository and also in our company's web server. Server access is restricted but i still think there could be a better way to use the master key password instead of hard coding it in the code.

I think this is not a topic for pykeepass - this is about how to do secure web development.

There are many solutions to this problem, but at the end, your web service needs to have access to the password, so you cannot keep it encrypted.

There are different ways to handle this:
- use tools like Hashicorp's Vault
- gitignore a file where the password is stored; read from that file; set proper permissions to that file; some deployment mechanism needs to put it place then
- https://12factor.net/ is also pretty popular; there the password is set as an environment variable, which many people oppose as not being max secure

**Comment by azinsharaf** [comment]
Thank you for the information. I will take a look.

**Comment by Evidlo** [comment]
> That is true. Users don't have access to the py file since they use the web service. But the script exists in our Git repository and also in our company's web server. Server access is restricted but i still think there could be a better way to use the master key password instead of hard coding it in the code.

It doesn't have to be in the code.  It can be in a separate file that your script reads from that you don't keep on git (add it to the gitignore to be safe).

The computer running the webserver will need the password stored somewhere in either case, but you can restrict access to that machine.
