### ISSUE TITLE
find_groups() and find_entries() path parameter doesn't match the doc

### ISSUE THREAD

**Issue by cbosdo** [libkeepass/pykeepass#313]
The documentation states that `find_groups()` and `find_entries()` `path` parameter are strings describing the full path, like `path/sub` but in reality an array with all the segments is needed.

For instance these don't work:

```py
kp.find_groups(path='Perso')
kp.find_entries(path="Perso/foo.bar")
```

While these do the work:

```py
kp.find_groups(path=['Perso'])
kp.find_entries(path=['Perso'], ['foo.bar'])
```

What needs fixing then, the doc or the code?

**Comment by Evidlo** [comment]
For the moment, README.md should be considered the canonical source of documentation.  I've removed the old `doc/` folder.
