### ISSUE TITLE
Accessing attachment data fails

### ISSUE THREAD

**Issue by harri-pasanen** [libkeepass/pykeepass#314]
In trying to read attachment data, my code does find the attachment, but throws an exception when trying to extract the data in it:

```
File "G:/harri/scripts/kp_access.py", line 112, in read_cert_from_keepass
    print(a.data)
  File "D:\Python38\lib\site-packages\pykeepass\attachment.py", line 45, in binary
    return self._kp.binaries[self.id]
  File "D:\Python38\lib\site-packages\pykeepass\pykeepass.py", line 692, in binaries
    base64.b64decode(elem.text),
  File "D:\Python38\lib\base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "D:\Python38\lib\base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

I could not reproduce the error with a trivial keepass repository I created from scratch, but it does appear with our real repository, which is maintained using KeePass 2.x.  

PyKeePass self.version seems to be (3,1) for the kdbx file.
pykeepass version is 4.0.3

**Comment by harri-pasanen** [comment]
Exporting the keepass repo to a xml and examining that, it seems the bug surfaces when there is a binary element with no text, like:

<Binary ID="5" Compressed="True" />

The fix would be something like the following in pykeepass.py

`            for elem in self._xpath('/KeePassFile/Meta/Binaries/Binary'):
                if elem.text:
                    if elem.get('Compressed') == 'True':
                        data = zlib.decompress(
                            base64.b64decode(elem.text),
                            zlib.MAX_WBITS | 32
                        )
                    else:
                        data = base64.b64decode(elem.text)
                else:
                    data = ''
                binaries.insert(int(elem.attrib['ID']), data)
`

**Comment by Evidlo** [comment]
Would you prefer empty attachments return `None` or an empty bytestring?
