### ISSUE TITLE
Question - How do I create a key file to be used with the keepass .kdbx file?

### ISSUE THREAD

**Issue by rtl19** [libkeepass/pykeepass#315]
What is the right way to create a key file which is used with a password when creating the new database file?

I attempted to create a key file by observing one that I had created using the keepass.exe open source executable.  It had a format something like:
```
<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
    <Meta>
        <Version>1.00</Version>
    </Meta>
    <Key>
        <Data>blahblahthisisntrealitsjustanexample</Data>
    </Key>
</KeyFile>
```
When I used the keyfile I created this way, it gave an error of 'incorrect padding' from the pykeepass.create_database("mydatabase.kdbx",password=mypassword,keyfile='filefromabove.xml')

What does 'incorrect padding' mean?  What did I do wrong?

**Comment by Evidlo** [comment]
I'm not able to reproduce this:

```
>>> !cat /tmp/test.key
<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
    <Meta>
        <Version>1.00</Version>
    </Meta>
    <Key>
        <Data>blahblahthisisntrealitsjustanexample</Data>
    </Key>
</KeyFile>

>>> create_database('/tmp/test.kdbx', 'password', keyfile='/tmp/test.key')
<pykeepass.pykeepass.PyKeePass at 0x7f746ea643a0>
```

**Comment by Evidlo** [comment]
You might also try a non-XML file as your key and see if that works.

**Comment by rtl19** [comment]
Thanks for your suggestions.  I was trying this on Windows 10 in Python 3.8.  I found that if I made my data string longer (like 75 chars), the padding error went away.  I have another question related to key files and transformed keys and such but I'll open that as another ticket.
