### ISSUE TITLE
Question - How do I save meta data there isn't yet a method for?

### ISSUE THREAD

**Issue by rtl19** [libkeepass/pykeepass#317]
I have a .kdbx database file that was created using the open source keepass.exe executable.  After looking at the database using your library, I noticed there were entries in there like:
'/KeePassFile/Meta/DefaultUserName'.  
If no formal method in the library exists for setting that value, is there a generic approach that I can use for any meta data value?

**Comment by Evidlo** [comment]
Yes, you should be able to do something like

``` python
# get DefaultUserName as an LXML element
default_username_elem =  kp._xpath('/KeePassFile/Meta/DefaultUserName', first=True)
default_username_elem.text = "foo"
```
