### ISSUE TITLE
Import Firefox password csv result in bad time data

### ISSUE THREAD

**Issue by Tuxilla** [libkeepass/pykeepass#327]
When I export passwords as CSV from Firefox 107.0 and import them into KeepassXC 2.6.6, I get wrong time data.

KeepassXC 2.6.6
Under Entries, Edit Entries, properties and modified "27 Sept. 54867 07:43:06" shown as modified in the overview "27.09.67 07:43".

In an older KeepassXC and Firefox version more parameters have been different, this .kdbx file causes a crash of Gnome Secrets. I think i have imported the CSV some time ago(2021).

Old unknown Version of KeepassXC.
Under Entries, Edit Entries, properties and created "31 Aug. 53372 12:41:32" shown as created in the overview "31.08.72 12:41".

I also found a segfault in the logs.
`Nov 24 11:34:01 kernel: keepassxc[5490]: segfault at d0 ip 0000573c522ab6a4 sp 00007fff56b9d9f8 error 4 in keepassxc[573c52228000+24a000]`

**Comment by A6GibKm** [comment]
Original report: https://gitlab.gnome.org/World/secrets/-/issues/439

**Comment by Evidlo** [comment]
The year 54867 is clearly an error, so how should we handle this?  The largest year supported by Python's `datetime` module is 9999, which is where the OverflowError is coming from.

**Comment by A6GibKm** [comment]
From my side showing a warning and returning None instead of  crashing is a good solution.

**Comment by A6GibKm** [comment]
I dont know if it is a good solution but from this question https://stackoverflow.com/questions/9516025/parsing-datetime-in-python there is a parse question that could raise an error.

**Comment by Evidlo** [comment]
@A6GibKm OK, so then is there any action required here?

**Comment by Evidlo** [comment]
> As I said, raising an error instead of crashing would be great.

Isn't that exactly what the `OverflowError`  raised by the datetime module is?

**Comment by Evidlo** [comment]
[This StackExchange](https://softwareengineering.stackexchange.com/a/391657) answer outlines when it's good to catch exceptions vs letting them bubble up higher in the stack:



> As a general principle, don't catch exceptions unless you know what to do with them. If MethodC throws an exception,  but MethodB has no useful way to handle it, then it should allow the exception to propagate up to MethodA.
>
> The only reasons why a method should have a catch and rethrow mechanism are:
>
>    - You want to convert one exception to a different one that is more meaningful to the caller above.
>    - You want to add extra information to the exception.
>    - You need a catch clause to clean up resources that would be leaked without one.
>
> Otherwise, catching exceptions at the wrong level tends to result in code that silently fails without providing any useful  feedback to the calling code (and ultimately the user of the software). The alternative of catching an exception and then immediately rethrowing it is pointless.

So I'm not sure that any of these three apply here.

**Comment by Evidlo** [comment]
> I would argue that as a library it is the responsibility of the user to determine what to do with the exception

So then Secrets is the 'user' here.  The recommendation from the linked SO post is that the exception is not handled by pykeepass and is caught by Secrets.

**Comment by A6GibKm** [comment]
But unless I am missing something, the crash happens at pykeepass side and I cannot catch it.

**Comment by Evidlo** [comment]
It doesn't matter where the exception happens, as long as one of the functions you are calling doesn't catch it.  pykeepass does not catch it:

``` python
from datetime import datetime, timedelta
from dateutil import tz
from pykeepass import PyKeePass
import base64
import struct

# manually set 'foobar_entry' time so that it overflows
kp = PyKeePass('test4.kdbx', 'password', 'test4.key')
e = kp.find_entries(title='foobar_entry', first=True)
t = e._xpath('Times/CreationTime', first=True)
overflow_seconds = 399999999999
t.text = base64.b64encode(struct.pack('<Q', overflow_seconds)).decode('utf-8')

# catch the exception
try:
    print('ctime:', e.ctime)
except OverflowError:
    print('got an overflow error')
```

``` python
>>> %run pykeepass_issue327.py
got an overflow error
```

**Comment by A6GibKm** [comment]
Ok I didn't know that. Thanks a lot, I thought it was a simple crash.
