### ISSUE TITLE
construct.core.ChecksumError: Error in path (parsing) -> cred_check

### ISSUE THREAD

**Issue by JoostW21111** [libkeepass/pykeepass#339]
Hi, I have creating an new database (Keepass) for the KeePassLibrary (Robotframework). When i running the test i get an CredentialsError:
![image](https://user-images.githubusercontent.com/130643234/231688510-89715f35-d816-42b4-9458-fa432b0e6a53.png)

I've tried different things
- create new database (kdbx)
- create and change keyx file
- change and modify path where de keepass database stands
- modify the extensions key or keyx file

Have I overlooked something that is causing Open Database not to work or is the someting in the pykeepass lib what is causing this error?

**Comment by Evidlo** [comment]
It's hard to say what might have caused this.  Can you provide example code or a database that works in KeepassXC but does not work with pykeepass?

**Comment by JoostW21111** [comment]
The credentials error is fixed.
I have changed the path names in the DIR (where the keepass files (kdbx, keyx) are located) and generated a new keyx file.
