### ISSUE TITLE
entry.set_custom_property("field_name",value) corrupts database

### ISSUE THREAD

**Issue by ManuelLatzo** [libkeepass/pykeepass#340]
If edit  KeePass v.2.5. 64-bit database with PyKeePass and save then database is corrupted. 
Tried with  KeePassXC 2.7.4  database and for no apparent reason database is corrupted sometimes too.

**Comment by Evidlo** [comment]
Can you provide some example code that reproduces this?  I tried this with the test database `test3.kdbx` and was not able to reproduce.

``` python
>>> from pykeepass import PyKeePass
>>> kp = PyKeePass('test3.kdbx', 'password', 'test3.key')
>>> e = kp.entries[1]
>>> e
Entry: "foobar_entry (foobar)"
>>> e.set_custom_property('foobar', '123')
>>> kp.save()
>>> kp = PyKeePass('test3.kdbx', 'password', 'test3.key')
```

**Comment by ManuelLatzo** [comment]
I found the workaround, use iso-8859-1 codepage and entry.save_history() is obligatory
