### ISSUE TITLE
4.0.4: no documentation? 🤔 

### ISSUE THREAD

**Issue by kloczek** [libkeepass/pykeepass#341]
Looks like in 4.0.4 content of the doc/ has been removed 🤔

**Comment by Evidlo** [comment]
Yes that was intentional, as the generated docs were out of date.  I've been slowly working on migrating to pdoc or pdoc3.

**Comment by kloczek** [comment]
Quoting from gawk info pages
"Documentation is like sex.
When it is good it is really good.
When it is bad it is better than nothing"

Now it is not possible even to improve that documentation.
