### ISSUE TITLE
Python 2 support (dependency on future)

### ISSUE THREAD

**Issue by frenzymadness** [libkeepass/pykeepass#345]
I have one simple question – Do you still need to support Python 2? I'm asking because this project uses `future`. `future`  will no longer work with Python 3.12 because `imp` module has been removed from stdlib and the situation will be even worse with 3.13 because the `lib2to3` which is the core of the `future` will be removed from stdlib as well.

It should be simple to remove the dependency on future, it's a good idea to do it, and I can help you with that if you want to.

**Comment by pwall2222** [comment]
Fixed by #350

**Comment by frenzymadness** [comment]
Great, thanks. Do you plan to do a new release?

**Comment by pwall2222** [comment]
> Great, thanks. Do you plan to do a new release?

Im just a contributor not the mantainer

**Comment by Evidlo** [comment]
Version 4.0.6 is released now.
