### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [libkeepass/pykeepass#356]
Is it possible next time on release new version make the github release to have entry on https://github.com/libkeepass/pykeepass/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by Evidlo** [comment]
Fixed by https://github.com/libkeepass/pykeepass/commit/fc1771ac884b0b1a6f3ac8e6da3bfe49da068e15
