### ISSUE TITLE
Feature Request: Add option to provide keyfile as bytes

### ISSUE THREAD

**Issue by jbrummer-vw** [libkeepass/pykeepass#363]
Currently keyfile must be a link to a real file. Using a Yubikey challenge response in upcoming Secrets we could use the bytes directly to open our database. The current workaround is to create a new file just for the keyfile handover.

Can we change the current implementation to bytes or add a new option for bytes transfer?

**Comment by jbrummer-vw** [comment]
@A6GibKm FYI

**Comment by A6GibKm** [comment]
If I am not mistaken, the current documentation suggests that you should be able to pass a bytes like object instead of a path, so it could be patched to do so.

**Comment by jbrummer-vw** [comment]
> If I am not mistaken, the current documentation suggests that you should be able to pass a bytes like object instead of a path, so it could be patched to do so.

Where is it mentioned in doc?

**Comment by A6GibKm** [comment]
See https://github.com/libkeepass/pykeepass/pull/201/files, filename takes a stream which is also useful (One can use a pythonio.BytesIO). But yeah, no mention about it for keyfiles.
