### ISSUE TITLE
It does not decodes entry.password for KeePass 2.53.1 64-bit 

### ISSUE THREAD

**Issue by ManuelLatzo** [libkeepass/pykeepass#368]
entry.password types 
kind of "s7C94AlInrk= "

password 12345678 decodes as o4pnKoMpFRI=

**Comment by ManuelLatzo** [comment]
the same issue for KeePass 2.55

**Comment by Faetu** [comment]
Same issue here. Do you have a workaround?

**Comment by ManuelLatzo** [comment]
> Same issue here. Do you have a workaround?
I am using custom_property methods, see below
```python
entry.set_custom_property("auth_password".encode('utf-8').decode('iso-8859-1','ignore'),value="password")
entry.save_history()
...
entry.get_custom_property('auth_password')
...
kp.save()
```

**Comment by Evidlo** [comment]
Can you give more detail on how to reproduce this or provide an example file?  I created a brand-new database with Keepass2 2.55 and was able to read the passwords with PyKeePass fine.

**Comment by ManuelLatzo** [comment]
Thanks for an update, agree version starting from 2.55 work just fine.
