### ISSUE TITLE
TOTP support

### ISSUE THREAD

**Issue by ILG2021** [libkeepass/pykeepass#375]
Hello, can we add support for TOTP?

**Comment by A6GibKm** [comment]
The library has TOTP support. You will need another library to generate the code for the current timestamp, but it is supported.

**Comment by ILG2021** [comment]
> The library has TOTP support. You will need another library to generate the code for the current timestamp, but it is supported.

Thanks for your reply. Can you gives a example code?

**Comment by Evidlo** [comment]
The README now has an example of this.
