### ISSUE TITLE
[change] - entry.tags to return empty list instead of None?

### ISSUE THREAD

**Issue by hicallmeal** [libkeepass/pykeepass#391]
Hey there, 

Hope not to overstep, but just in my usage, I found it a bit inconvenient that  `entry.tags` returns `None`, if no tags are present. 
I feel like returning an empty list makes more sense. 

Similarly to #175 , with `entry.history`

Could be done if [this](https://github.com/libkeepass/pykeepass/blob/66bc40952a121c0aacd809d1680368eae1ecf283/pykeepass/entry.py#L237) was changed to `return val.replace(',', ';').split(';') if val else []`

My usage involves searching for entries (via title / group / tags) then checking whether a different tag is present. 
`if 'nTag' in entry.tags'

If it's thought to be of merit, perhaps other `properties` should be looked at as well?
(where a change like this would make sense)

Apologies, I'm not sure whether this would break anything, it's certainly a change that could affect users.

**Comment by hicallmeal** [comment]
If it's thought to be of merit, perhaps other @properties should be looked as well? 
(where a change like this would make sense)

**Comment by Evidlo** [comment]
This makes sense to me.  Heads up to @A6GibKm @janbrummer  for a breaking change.

**Comment by Evidlo** [comment]
Fixed in master.  To be released in 4.1.0
