### ISSUE TITLE
Creating new databases

### ISSUE THREAD

**Issue by Evidlo** [libkeepass/pykeepass#8]
Is there a way to create a new database file?  I see that the database file is read as soon as a `PyKeePass` object is initialized.

**Comment by pschmitt** [comment]
No. PyKeePass only works with existing databases.

**Comment by Evidlo** [comment]
Would you be willing to merge such a feature?  It could be something as simple as shipping an empty database and copying the file to the desired location when the user calls `create_database`.

**Comment by pschmitt** [comment]
Yeah sure. My original workflow did not require to create databases, but that's still a feature that pykeepass needs.

**Comment by ichbestimmtnicht** [comment]
I like to recommend https://app.keeweb.info/
Just klick New
Make your entries or leave it blank
click low left corner "New[number]" to go to settings.
set your password and or encryption rounds....
save to file
done. :D

**Comment by Evidlo** [comment]
Fixed in 3.2.0
